[tasks.fix]
depends = ["go-fix", "go-fmt", "go-mod-tidy"]

[tasks.go-fix]
run = "go fix ./..."

[tasks.go-fmt]
run = "go fmt ./..."

[tasks.go-mod-tidy]
run = "go mod tidy"

[tasks.lint]
depends = ["check-sumtype", "constable", "nilaway", "staticcheck", "vet"]

[tasks.check-sumtype]
run = "go tool go-check-sumtype ./..."

[tasks.constable]
run = "go run ./cmd/constable ./..."

[tasks.nilaway]
run = "go tool nilaway -include-pkgs='github.com/nnutter' ./..."

[tasks.staticcheck]
run = "go tool staticcheck ./..."

[tasks.vet]
run = "go vet ./..."

[tasks.coverage-data]
run = "go test -coverprofile coverage.out ./..."

[tasks.coverage-html]
depends = ["coverage-data"]
run = "go tool cover -html=coverage.out -o coverage.html"

[tasks.coverage]
depends = ["coverage-html"]
run = "xdg-open coverage.html 2>/dev/null || open coverage.html"

[tasks.tests]
run = "go test -cover ./..."

[tools]
go = "1.27.0"
