[tasks.check-sumtype]
run = "go-check-sumtype ./..."

[tasks.coverage-data]
run = "go test -coverprofile coverage.out ./..."

[tasks.coverage-html]
depends = ["coverage-data"]
run = "go tool cover -html=coverage.out -o coverage.html"

[tasks.coverage]
depends = ["coverage-html"]
run = "xdg-open coverage.html 2>/dev/null || open coverage.html"

[tasks.fix]
run = "go fix ./..."

[tasks.fixers]
depends = ["fix", "fmt", "mod-tidy"]

[tasks.fmt]
run = "go fmt ./..."

[tasks.mod-tidy]
run = "go mod tidy"

[tasks.nilaway]
run = "nilaway -include-pkgs='github.com/nnutter' ./..."

[tasks.constable]
run = "go run ./cmd/constable ./..."

[tasks.staticcheck]
run = "staticcheck ./..."

[tasks.linters]
depends = ["check-sumtype", "nilaway", "staticcheck", "vet"]

[tasks.tests]
run = "go test -cover ./..."

[tasks.vet]
run = "go vet ./..."

[tools]
go = "1.26.3"
"go:github.com/alecthomas/go-check-sumtype/cmd/go-check-sumtype" = "v0.3.1"
"go:go.uber.org/nilaway/cmd/nilaway" = "latest"
"go:golang.org/x/tools/gopls" = "v0.22.0"
"go:honnef.co/go/tools/cmd/staticcheck" = "v0.7.0"
